name: Publish to PyPI and GitHub Releases

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sklearn_metrics
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
      contents: write  # Needed for github release

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel
        pip install -e .
    
    - name: Build package
      run: |
        # Clean any previous builds
        rm -rf dist/ build/ *.egg-info
        # Build package
        python -m build
        # List contents of dist directory
        ls -l dist/
    
    - name: Check package
      run: |
        twine check dist/*
    
    - name: Test wheel installation
      run: |
        pip install dist/*.whl
        python -c "from sklearn_metrics import __version__; print(__version__)"
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
    
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 